// Day 3 follows the 2026.08.17-2027.04.30 syllabus: Phase 1 foundation building.
days.day3 = {
  label: "Day 3 · 2026.08.19", date: "2026-08-19",
  title: "Day 3｜Academic IELTS 7.0 + NZTC GD Readiness",
  theme: "IELTS：Urban Transport & Sustainable Cities｜NZTC：Play-based Learning",
  time: "标准版 90 分钟",
  tasks: [
    ["复习", "Day 2 词汇、因果语法、听读定位与写说输出", "10 分钟"],
    ["词汇 + 语法", "城市交通学术词汇 + 比较与对照表达", "15 分钟"],
    ["雅思听力", "Section 2 公共交通说明 + Note Completion", "15 分钟"],
    ["雅思阅读", "城市出行短文 + Matching Headings", "15 分钟"],
    ["雅思写作", "Academic Task 1 表格：通勤方式变化", "10 分钟"],
    ["雅思口语", "Part 2：一次公共交通出行", "5 分钟"],
    ["NZTC GD 适应", "Play-based Learning 与观察表达", "20 分钟"]
  ],
  review: `
    <h3>Day 2 完整复习｜基础积累阶段</h3><div class='review-modules'>
    <article class='review-module-card'><h4>1. 五个重点词｜回忆 + 搭配 + 造句</h4><table><thead><tr><th>单词</th><th>中文</th><th>搭配</th><th>输出提示</th></tr></thead><tbody><tr><td>significant</td><td>显著的；重要的</td><td>significant impact</td><td>There was a significant increase in…</td></tr><tr><td>factor</td><td>因素</td><td>a key factor</td><td>One key factor is…</td></tr><tr><td>evidence</td><td>证据</td><td>research evidence</td><td>Evidence indicates that…</td></tr><tr><td>impact</td><td>影响</td><td>have an impact on</td><td>…has a positive impact on…</td></tr><tr><td>participate</td><td>参与</td><td>participate in</td><td>People should participate in…</td></tr></tbody></table><div class='answer'><strong>任务：</strong>逐词说出词性、中文和搭配，再任选 3 词造句。<br><strong>参考：</strong>Research evidence indicates that active participation can have a significant impact on community wellbeing.</div></article>
    <article class='review-module-card'><h4>2. Quick Words｜15 词回忆</h4><table><thead><tr><th>变化与数据</th><th>研究与决策</th><th>社会与方法</th></tr></thead><tbody><tr><td>increase / decline / proportion / benefit / challenge</td><td>policy / research / survey / indicate</td><td>access / community / environment / diverse / approach / support</td></tr></tbody></table><div class='answer'><strong>中译英：</strong>a significant increase；a gradual decline；a large proportion of；carry out research；a practical approach。<br><strong>输出：</strong>A survey indicates that a large proportion of residents support the new policy.</div></article>
    <article class='review-module-card'><h4>3. Grammar｜因果关系</h4><p>1. The activity was cancelled ______ heavy rain.<br>2. Children learn social skills ______ they interact with others.<br>3. The evidence was limited; ______, the conclusion was revised.</p><div class='answer'><strong>答案：</strong>because of；because；therefore。because + 完整句；because of + 名词短语；therefore 引出结果。</div></article>
    <article class='review-module-card'><h4>4. 听力与阅读｜定位和同义替换</h4><p><strong>听力：</strong>completed ≠ invited；feedback = opinions；opportunities = chances。确认数字对应对象后再作答。</p><p><strong>判断：</strong>原文 Some parents are concerned about safety；题目 All parents believe outdoor play is completely safe。</p><div class='answer'><strong>答案：</strong>False。some 与 all 范围不同，concerned 与 completely safe 意思相反。Not Given 只用于原文信息不足。</div></article>
    <article class='review-module-card'><h4>5. 写作、口语与 NZTC｜主动输出</h4><p><strong>写作：</strong>复述 discussion essay 四段结构。<br><strong>口语：</strong>用“观点—原因—例子”回答 Should cities provide more public spaces?<br><strong>NZTC：</strong>说出 Observation → Learning → Next Step 与 Te Whāriki 五个 strands。</p><div class='answer'>While public spaces require investment, they benefit communities because they provide accessible places for exercise and interaction.<br><strong>Strands：</strong>Wellbeing, Belonging, Contribution, Communication, Exploration。</div></article></div>`,
  english: `
    <div class='details-list'><details open><summary>1. 重点词汇卡｜Academic Vocabulary</summary><p>今天的 IELTS 主题是“城市与交通”。</p><div class='word-grid'>
    <article class='word-card'><h3>sustainable</h3><p>/səˈsteɪnəbəl/ · adjective · 可持续的</p><p><strong>搭配：</strong>sustainable transport / sustainable development</p><p><strong>基础：</strong>The city needs a sustainable transport system.</p><p><strong>主题：</strong>Safe cycle lanes can make urban travel more sustainable.</p><p><strong>提示：</strong>也表示能够长期维持。</p><p><strong>My Sentence：</strong>______ is a sustainable way to ______.</p></article>
    <article class='word-card'><h3>infrastructure</h3><p>/ˈɪnfrəstrʌktʃə(r)/ · noun · 基础设施</p><p><strong>搭配：</strong>transport infrastructure / invest in infrastructure</p><p><strong>基础：</strong>The government plans to invest in infrastructure.</p><p><strong>主题：</strong>Well-designed infrastructure makes travel safer and more efficient.</p><p><strong>提示：</strong>通常作不可数名词。</p><p><strong>My Sentence：</strong>The city should invest in ______ infrastructure.</p></article>
    <article class='word-card'><h3>congestion</h3><p>/kənˈdʒestʃən/ · noun · 拥堵</p><p><strong>搭配：</strong>traffic congestion / reduce congestion</p><p><strong>基础：</strong>Congestion is worst during the morning peak.</p><p><strong>主题：</strong>Lower bus fares may encourage drivers to use public transport and reduce congestion.</p><p><strong>同义：</strong>heavy traffic。</p><p><strong>My Sentence：</strong>One way to reduce congestion is to ______.</p></article>
    <article class='word-card'><h3>commute</h3><p>/kəˈmjuːt/ · verb / noun · 通勤；通勤路程</p><p><strong>搭配：</strong>daily commute / commute by train</p><p><strong>基础：</strong>She commutes to work by train.</p><p><strong>主题：</strong>A long commute can affect health and productivity.</p><p><strong>词族：</strong>commuter = 通勤者。</p><p><strong>My Sentence：</strong>I commute to ______ by ______.</p></article>
    <article class='word-card'><h3>accessible</h3><p>/əkˈsesəbəl/ · adjective · 易到达的；可使用的</p><p><strong>搭配：</strong>accessible public transport / accessible to residents</p><p><strong>基础：</strong>The station is accessible by bus.</p><p><strong>主题：</strong>Public transport should be affordable and accessible to outer suburbs.</p><p><strong>词族：</strong>access / accessible。</p><p><strong>My Sentence：</strong>______ should be accessible to ______.</p></article></div></details>
    <details class='quick-words-card'><summary>2. Quick Words｜快速积累 15 词</summary><table><thead><tr><th>单词</th><th>词性与发音</th><th>中文</th><th>常用搭配</th></tr></thead><tbody>
    <tr><td>pedestrian</td><td>n. /pəˈdestriən/</td><td>行人</td><td>pedestrian crossing</td></tr><tr><td>cyclist</td><td>n. /ˈsaɪklɪst/</td><td>骑行者</td><td>protect cyclists</td></tr><tr><td>emission</td><td>n. /ɪˈmɪʃən/</td><td>排放物</td><td>carbon emissions</td></tr><tr><td>transport</td><td>n. /ˈtrænspɔːt/</td><td>交通</td><td>public transport</td></tr><tr><td>fare</td><td>n. /feə(r)/</td><td>票价</td><td>bus fare</td></tr><tr><td>route</td><td>n. /ruːt/</td><td>路线</td><td>bus route</td></tr><tr><td>capacity</td><td>n. /kəˈpæsəti/</td><td>容量</td><td>increase capacity</td></tr><tr><td>peak</td><td>n./adj. /piːk/</td><td>高峰</td><td>peak hours</td></tr><tr><td>efficient</td><td>adj. /ɪˈfɪʃənt/</td><td>高效的</td><td>efficient system</td></tr><tr><td>alternative</td><td>n./adj. /ɔːlˈtɜːnətɪv/</td><td>替代方案</td><td>an alternative to driving</td></tr><tr><td>urban</td><td>adj. /ˈɜːbən/</td><td>城市的</td><td>urban area</td></tr><tr><td>rural</td><td>adj. /ˈrʊərəl/</td><td>乡村的</td><td>rural community</td></tr><tr><td>expand</td><td>v. /ɪkˈspænd/</td><td>扩大</td><td>expand the network</td></tr><tr><td>reduce</td><td>v. /rɪˈdjuːs/</td><td>减少</td><td>reduce emissions</td></tr><tr><td>investment</td><td>n. /ɪnˈvestmənt/</td><td>投资</td><td>public investment</td></tr></tbody></table><div class='answer'><strong>填空：</strong>Better bus ______ make transport accessible. Cycle lanes protect ______ and reduce carbon ______. Public ______ can expand capacity.<br><strong>答案：</strong>routes；cyclists；emissions；investment。任选 5 词造句。</div></details>
    <details class='grammar-card'><summary>3. Grammar｜比较与对照表达</summary><table><thead><tr><th>结构</th><th>规则</th><th>例句</th></tr></thead><tbody><tr><td>whereas</td><td>同句直接对照</td><td>Car use fell, whereas bus use increased.</td></tr><tr><td>while + 分句</td><td>句首或句中对比</td><td>While cars remained dominant, their share declined.</td></tr><tr><td>compared with + 名词</td><td>后接比较基准</td><td>Cycling was higher compared with 2000.</td></tr><tr><td>By contrast</td><td>另起一句突出反向趋势</td><td>Car use declined. By contrast, bus use rose.</td></tr><tr><td>respectively</td><td>数值依次对应</td><td>Bus and cycle shares were 28% and 15%, respectively.</td></tr></tbody></table><div class='answer'><strong>纠错：</strong>❌ Compared with car use declined… ✅ Compared with the figure for 2000, car use was lower in 2020.<br><strong>练习：</strong>Cars were 60%; buses were 20%.（whereas）<br><strong>答案：</strong>Cars accounted for 60%, whereas buses accounted for 20%.</div></details>
    <details><summary>4. 雅思听力｜Section 2 公共交通说明</summary><p>1. Buses leave every ______ minutes. 2. Adult fare £______. 3. Tickets available through city ______. 4. Stop closed because of ______ work.</p><p><strong>听读文本：</strong>From Monday, buses on Route 8 will run every twelve minutes during peak hours, instead of every twenty minutes. An adult fare remains two pounds forty, while students pay one pound sixty. Weekly tickets are available through the city transport app. Park Street will close for three weeks because of road repair work.</p><div class='answer'><strong>答案：</strong>12；2.40；transport app；road repair。<br><strong>干扰：</strong>20 是旧间隔；1.60 是学生票；three weeks 是时长。<br><strong>同义：</strong>run every = leave every；remains = still costs。听读两遍后复述 3 句。</div></details>
    <details><summary>5. 雅思阅读｜Matching Headings</summary><p><strong>标题：</strong>i Why adding roads may fail　ii Fair access to essential services　iii Health benefits beyond transport　iv The end of private cars　v Using information to improve journeys</p><p><strong>A</strong> Cities often widen roads, yet extra capacity encourages more driving, so congestion returns. Road construction alone is not a lasting solution.</p><p><strong>B</strong> People who cannot drive need reliable services to reach work, education and healthcare. Affordable fares and outer-suburb routes can reduce inequality.</p><p><strong>C</strong> Walking and cycling reduce emissions and turn daily journeys into physical activity, supporting heart health and reducing stress.</p><p><strong>D</strong> Authorities use anonymous travel data to identify crowded routes. Timetable changes and live arrival information can improve journeys without new infrastructure.</p><div class='answer'><strong>答案：</strong>A–i；B–ii；C–iii；D–v；iv 不使用。标题要概括整段，不能只按相同单词匹配。</div></details>
    <details><summary>6. 雅思写作｜Academic Task 1 表格</summary><p><strong>题目：</strong>下表为某市三种通勤方式占比。概括主要特征并比较。</p><table><thead><tr><th>方式</th><th>2000</th><th>2010</th><th>2020</th></tr></thead><tbody><tr><td>Car</td><td>60%</td><td>55%</td><td>45%</td></tr><tr><td>Bus</td><td>20%</td><td>23%</td><td>28%</td></tr><tr><td>Cycling</td><td>5%</td><td>8%</td><td>15%</td></tr></tbody></table><div class='answer'><strong>Introduction：</strong>The table compares the proportions of commuter journeys made by car, bus and bicycle in three years.<br><strong>Overview：</strong>Overall, cars remained the most common mode, although their share declined. By contrast, bus use and cycling increased, with cycling showing the fastest growth.<br><strong>比较：</strong>Car use fell from 60% to 45%, whereas bus travel rose by eight percentage points.<br><strong>任务：</strong>写 introduction + overview + 两个比较句（80—100 词），不解释原因。</div></details>
    <details><summary>7. 雅思口语｜Part 2 公共交通出行</summary><p><strong>Cue Card：</strong>Describe a journey you made by public transport: where, what transport, who with, and how you felt.</p><p><strong>笔记：</strong>city centre；metro + bus；friend；cheap but crowded；missed a stop。</p><div class='answer'><strong>示例：</strong>I travelled to the city centre with a friend. We took the metro and changed to a bus. The metro was fast and affordable, whereas the bus was crowded during the evening peak. We missed our stop because we were unfamiliar with the route. Even so, public transport was a convenient alternative to driving.<br><strong>任务：</strong>准备 1 分钟，连续说 90 秒；第二遍加入 accessible、congestion 或 whereas。</div></details></div>`,
  ece: `<h3>Play-based Learning｜以游戏为基础的学习</h3><p><strong>中文：</strong>儿童通过主动、有意义的游戏探索材料、关系与想法。教师观察兴趣，在合适时用材料、提问和语言延伸学习。</p><p><strong>English：</strong>Play-based learning allows children to explore ideas through active and meaningful play. The teacher extends learning through thoughtful questions, materials and responsive interaction.</p><table><thead><tr><th>术语</th><th>中文</th><th>课堂理解</th></tr></thead><tbody><tr><td>play-based learning</td><td>游戏式学习</td><td>学习发生在主动游戏中</td></tr><tr><td>child-led play</td><td>儿童主导的游戏</td><td>儿童决定方向，教师回应</td></tr><tr><td>learning disposition</td><td>学习倾向</td><td>好奇、坚持、合作、自信</td></tr><tr><td>scaffolding</td><td>支架式支持</td><td>提供刚好足够的帮助</td></tr><tr><td>open-ended materials</td><td>开放性材料</td><td>积木、布、自然材料等多种玩法</td></tr></tbody></table><p><strong>场景：</strong>A child built a bridge with blocks, tested toy cars, and rebuilt the base after it fell.</p><div class='answer'><strong>Observation：</strong>I observed the child building, testing and changing the bridge.<br><strong>Learning：</strong>This play supported problem-solving, persistence and early mathematical thinking.<br><strong>Next Step：</strong>I would provide bridge photos and invite the child to explain which design is strongest.<br><strong>教师语言：</strong>What do you notice? / What could you try next?</div><p><strong>练习：</strong>The child showed persistence when ______. I supported the learning by ______. Next time, I would ______.</p>`
};

renderDay();
renderVocabulary();
