// Day 4–Day 9：基础积累阶段。内容按 Academic IELTS 真实题型轮换，NZTC 仅作双语适应支持。
(function () {
  const days4to9 = [
    {
      key:"day4", label:"Day 4 · 2026.08.20", date:"2026-08-20", theme:"Health & Lifestyle｜健康、生活方式与公共健康", previous:"Day 3 教育科技词汇、让步对比与判断题定位", eceTitle:"Wellbeing & Emotional Regulation｜身心健康与情绪调节",
      focus:[
        ["wellbeing","n. /ˈwelbiːɪŋ/","身心健康；福祉","promote wellbeing / mental wellbeing","Regular exercise promotes physical wellbeing.","Access to green spaces can improve the wellbeing of city residents.","注意：常写作 well-being，也可作 wellbeing。","______ can promote the wellbeing of ______."],
        ["sedentary","adj. /ˈsedəntri/","久坐的；久坐少动的","sedentary lifestyle / sedentary behaviour","Office workers may have a sedentary lifestyle.","A sedentary routine is associated with several long-term health risks.","用于描述生活方式，不能直接说 sedentary people。","A sedentary lifestyle may lead to ______."],
        ["nutrition","n. /njuːˈtrɪʃn/","营养；营养学","balanced nutrition / poor nutrition","Good nutrition is important for children.","Public health campaigns can improve nutrition by providing clear information.","通常不可数。","Good nutrition helps people to ______."],
        ["prevention","n. /prɪˈvenʃn/","预防","disease prevention / prevention of","Prevention is better than treatment.","Investment in prevention may reduce pressure on public hospitals.","prevention of + 名词；prevent + 名词/doing。","The prevention of ______ requires ______."],
        ["obesity","n. /əʊˈbiːsəti/","肥胖","childhood obesity / reduce obesity","Obesity can affect a person's health.","Urban design that encourages walking may help reduce childhood obesity.","敏感健康话题中使用中性、客观语气。","One way to reduce obesity is to ______."]
      ],
      quick:[
        ["diet","n. /ˈdaɪət/","饮食；日常饮食","balanced diet"],["exercise","n./v. /ˈeksəsaɪz/","锻炼；运动","regular exercise"],["treatment","n. /ˈtriːtmənt/","治疗","medical treatment"],["symptom","n. /ˈsɪmptəm/","症状","common symptom"],["risk","n. /rɪsk/","风险","health risk"],["stress","n./v. /stres/","压力","reduce stress"],["routine","n. /ruːˈtiːn/","日常规律","daily routine"],["moderate","adj. /ˈmɒdərət/","适度的","moderate exercise"],["consume","v. /kənˈsjuːm/","摄入；消费","consume sugar"],["medical","adj. /ˈmedɪkl/","医学的；医疗的","medical advice"],["habit","n. /ˈhæbɪt/","习惯","healthy habit"],["physical","adj. /ˈfɪzɪkl/","身体的；物理的","physical activity"],["mental","adj. /ˈmentl/","心理的","mental health"],["recover","v. /rɪˈkʌvə(r)/","恢复","recover from illness"],["priority","n. /praɪˈɒrəti/","优先事项","public health priority"]
      ],
      grammar:{title:"建议、义务与程度表达", goal:"在健康类 Task 2 与口语中准确区分 should、need to、have to、may 和 tend to。", rows:[["should + 动词原形","建议，不表示强制","Governments should provide clear nutrition advice."],["need to + 动词原形","必要性，主语可为人或事物","People need to develop healthier routines."],["have to + 动词原形","外部规则或不得不","Patients may have to attend regular check-ups."],["may / can + 动词原形","可能性或能力","A sedentary lifestyle may increase health risks."],["tend to + 动词原形","一般趋势，不是绝对","People tend to exercise less when they work long hours."]], error:"❌ People should to exercise.  ✅ People should exercise.\n❌ Obesity can to cause problems.  ✅ Obesity can cause problems.", exercise:"1. Long working hours make exercise difficult.（用 may）\n2. Schools provide healthy meals.（用 should）\n3. People with little free time exercise less.（用 tend to）", answer:"1. Long working hours may make exercise difficult.\n2. Schools should provide healthy meals.\n3. People with little free time tend to exercise less."},
      listening:{title:"Section 1｜健身中心会员登记", scenario:"日常服务场景。正式考试 Listening Part 1 常见为两人对话；先读题并预测姓名、数字、日期或名词。", questions:["1. The joining fee is £______. ","2. The monthly membership costs £______.","3. The beginner class is held on ______ evenings.","4. Members need to bring a ______ for the swimming pool."], text:"Receptionist: The joining fee is fifteen pounds, and the monthly membership is thirty-two pounds. The beginner fitness class takes place on Tuesday evenings at six. If you would like to use the pool, please bring your own towel. Lockers are available, but you need a one-pound coin for the key.", answer:"15；32；Tuesday；towel。", substitution:"joining fee = fee to become a member；takes place = is held；bring your own = take with you。", task:"先遮住答案完成填空；再听读两遍，圈出价格、日期和物品。最后用 3 句复述会员信息。"},
      reading:{title:"Matching Information｜公共健康项目", type:"题型提示：题目问的是“哪一段包含某条具体信息”，重点找信息位置，不必概括整段主旨。", passage:["A  A city health department has introduced free weekend walking groups in several neighbourhood parks. Local volunteers lead routes of different lengths, so older residents and beginners can choose a suitable pace.","B  A separate programme works with supermarkets. It places simple labels beside common foods and provides recipe cards that show how to prepare low-cost meals with less salt and sugar.","C  At local workplaces, employers can apply for small grants to buy standing desks or organise short activity breaks. The project is designed for people whose jobs involve long periods of sitting.","D  Health clinics now send text-message reminders to patients who miss regular health checks. The messages also include a link to book another appointment."], questions:["1. a project intended for people with sedentary jobs", "2. help for people who want to choose food more carefully", "3. a system that contacts people after they fail to attend", "4. an activity with options for different physical abilities"], answer:"1 C；2 B；3 D；4 A。定位词：sitting → sedentary；labels/recipes → choose food；miss checks → fail to attend；different lengths/pace → different abilities。"},
      writing:{title:"Academic Task 1｜折线图：运动频率变化", prompt:"下图显示 2000、2010 和 2020 年某城市成年人每周进行三次及以上运动的比例。概括主要特征并比较。", table:[["群体","2000","2010","2020"],["18–29 岁","42%","48%","55%"],["30–49 岁","35%","38%","44%"],["50+ 岁","20%","26%","33%"]], plan:"Introduction：改写图表主题。Overview：三个年龄组均上升；18–29 岁始终最高；50+ 增幅最大。Body：先写 18–29 与 30–49，再写 50+ 的起点和终点。", band:"The proportion of adults aged 18–29 who exercised regularly rose steadily from 42% to 55%. By comparison, the figure for those aged 50 and over increased by 13 percentage points.", task:"写 1 句 introduction、1 句 overview 和 3 句比较。不要解释‘为什么’人们更常运动。"},
      speaking:{title:"Part 1｜Health and Exercise", questions:["Do you do any exercise?", "What do people in your area do to stay healthy?", "Do you think people today have healthier lifestyles than in the past?"], structure:"直接回答 → 原因 → 具体例子。避免只说 Yes, I do；至少补充一个频率、地点或习惯。", sample:"Yes, I try to exercise three times a week, usually by walking briskly after work. It helps me reduce stress, and it is easier to maintain than a complicated fitness routine.", task:"选择其中两题录音，每题 30–40 秒。回听时标出一个连接词和一个健康词汇。"},
      ece:{zh:"幼儿的 wellbeing 不只是身体健康，也包括安全感、情绪表达、休息和与他人的积极关系。教师先观察孩子的状态，再提供恰当支持。", en:"Wellbeing includes children's physical health, emotional security, rest and positive relationships. Teachers observe how a child is feeling and respond with appropriate support.", terms:[["emotional regulation","情绪调节","帮助儿童识别、表达并逐步管理情绪"],["secure relationship","安全关系","稳定、可回应的成人关系"],["calm-down space","平静角","可短暂休息、整理情绪的安静区域"]], scenario:"A child becomes upset when another child takes a toy. 练习：I noticed that… / The child may have felt… / I would support the child by…"}
    },
    {
      key:"day5", label:"Day 5 · 2026.08.21", date:"2026-08-21", theme:"Environment & Climate｜环境、气候与个人行动", previous:"Day 4 健康词汇、建议义务表达与 Matching Information", eceTitle:"Sustainable Practice｜可持续实践与自然探索",
      focus:[
        ["biodiversity","n. /ˌbaɪəʊdaɪˈvɜːsəti/","生物多样性","protect biodiversity / loss of biodiversity","Biodiversity is important for healthy ecosystems.","Protecting urban green areas can support local biodiversity.","bio- 表示生命，diversity 表示多样性。","______ can help protect biodiversity."],
        ["conservation","n. /ˌkɒnsəˈveɪʃn/","保护；节约","wildlife conservation / water conservation","Conservation requires long-term planning.","Water conservation is essential in regions affected by drought.","conserve 是动词：节约、保护。","Conservation of ______ is important because ______."],
        ["renewable","adj. /rɪˈnjuːəbl/","可再生的","renewable energy / renewable source","Solar power is a renewable source of energy.","Governments can reduce emissions by investing in renewable energy.","反义：non-renewable。","______ is a renewable alternative to ______."],
        ["consumption","n. /kənˈsʌmpʃn/","消费；消耗","energy consumption / reduce consumption","Energy consumption rises in cold weather.","Household energy consumption can be reduced through better insulation.","来自 consume；常作不可数。","The consumption of ______ has increased because ______."],
        ["regulation","n. /ˌreɡjuˈleɪʃn/","法规；管理；调节","environmental regulation / strict regulations","Regulations can limit industrial pollution.","Environmental regulations may encourage companies to use cleaner technology.","rule 是日常规则，regulation 更正式。","Stricter regulations could reduce ______."]
      ],
      quick:[["climate","n. /ˈklaɪmət/","气候","climate change"],["carbon","n. /ˈkɑːbən/","碳","carbon footprint"],["pollution","n. /pəˈluːʃn/","污染","air pollution"],["recycle","v. /ˌriːˈsaɪkl/","回收利用","recycle waste"],["waste","n./v. /weɪst/","废物；浪费","household waste"],["resource","n. /rɪˈsɔːs/","资源","natural resources"],["protect","v. /prəˈtekt/","保护","protect wildlife"],["damage","n./v. /ˈdæmɪdʒ/","损害","environmental damage"],["global","adj. /ˈɡləʊbl/","全球的","global warming"],["species","n. /ˈspiːʃiːz/","物种","endangered species"],["solar","adj. /ˈsəʊlə(r)/","太阳能的","solar energy"],["sustainable","adj. /səˈsteɪnəbəl/","可持续的","sustainable lifestyle"],["disposal","n. /dɪˈspəʊzl/","处置","waste disposal"],["reduce","v. /rɪˈdjuːs/","减少","reduce emissions"],["campaign","n. /kæmˈpeɪn/","宣传活动","public campaign"]],
      grammar:{title:"条件句与结果表达", goal:"用 if、unless、as a result 和 lead to 说明环境问题的条件与结果。", rows:[["if + 现在时, will + 动词","真实可能条件","If cities improve public transport, emissions will fall."],["unless + 现在时","除非；= if ... not","Unless people change habits, waste will continue to rise."],["lead to + 名词/动名词","导致某结果","Excessive consumption can lead to environmental damage."],["as a result","因此，连接两个句子","Recycling facilities are limited. As a result, more waste is sent to landfill."]], error:"❌ If people will recycle, pollution will fall.  ✅ If people recycle, pollution will fall.\n❌ lead to increase pollution  ✅ lead to increased pollution / lead to increasing pollution", exercise:"1. Governments invest in solar energy. Emissions fall.（if）\n2. People reduce consumption. Resources will be exhausted.（unless）\n3. Cars are used excessively. Air quality becomes worse.（lead to）", answer:"1. If governments invest in solar energy, emissions will fall.\n2. Unless people reduce consumption, resources will be exhausted.\n3. Excessive car use can lead to poorer air quality."},
      listening:{title:"Section 4｜城市绿地讲座笔记", scenario:"学术单人讲座。Part 4 常要求抓定义、原因、研究发现；答案按录音顺序出现。", questions:["1. Green roofs can reduce the temperature of ______.","2. They provide habitats for insects and small ______.","3. One study found that green roofs can hold rain ______.","4. The speaker recommends training for building ______."], text:"Lecturer: Green roofs are areas of vegetation installed on the tops of buildings. They can lower the temperature of the building itself during hot weather. They also create habitats for insects and small birds. In addition, the soil and plants hold rainwater, which reduces pressure on city drainage systems. However, green roofs need regular maintenance, so the speaker recommends basic training for building managers.", answer:"buildings / the building；birds；water；managers。", substitution:"installed on = placed on；hold rainwater = keep rain water；maintenance = regular care。", task:"第一次只完成题目；第二次在文本中划出名词同义替换；第三次用中文说明绿化屋顶的两项好处。"},
      reading:{title:"True / False / Not Given｜塑料与消费者选择", type:"先判断题目是否与原文含义相同或相反；原文没有明确比较、数字或因果时才选 Not Given。", passage:["Many consumers now carry reusable bags and bottles, but individual action alone cannot solve plastic pollution. Packaging is often chosen before a product reaches a shop, so manufacturers and retailers also influence the amount of waste created. Some cities have introduced charges for single-use bags, and studies have reported lower use after such charges were introduced. However, a charge does not automatically improve recycling systems. Effective waste management also depends on collection, sorting and public information. In some areas, people are unsure which materials can be recycled, so clear labels are important."], questions:["1. Individual consumers are the only group responsible for plastic waste.","2. Charges for single-use bags have reduced their use in some places.","3. A bag charge always improves local recycling systems.","4. The passage gives the exact percentage reduction in bag use.","5. Clear labelling can help people recycle correctly."], answer:"1 False：manufacturers and retailers also influence waste。2 True：studies reported lower use。3 False：does not automatically improve systems。4 Not Given：没有百分比。5 True：clear labels are important。"},
      writing:{title:"Academic Task 2｜环境问题的原因与解决方案", prompt:"In many countries, household waste is increasing rapidly. What are the causes of this problem, and what measures could be taken to solve it?", plan:"引言：改写题目，概览原因与解决方向。主体 1：方便包装、过度消费、缺乏分类意识。主体 2：生产端减少包装、政府改善回收与收费、消费者改变习惯。结论：双方共同承担责任。", band:"A major cause is the widespread use of disposable packaging, which allows consumers to purchase products conveniently but creates unnecessary waste. Governments could address this by requiring clearer recycling labels and charging for certain single-use items.", task:"写 thesis 句 + 原因段 4 句。每个原因后必须解释‘为什么会增加垃圾’。"},
      speaking:{title:"Part 2｜一次保护环境的行动", questions:["Describe something you have done to help the environment.","You should say what you did, why you did it, whether it was difficult, and explain how you felt about it."], structure:"用过去时讲清场景，再用 because 解释动机，最后评价效果。", sample:"Last year, I started carrying a reusable bottle and shopping bag. It was a small change, but it reduced the number of disposable items I used each week. At first I sometimes forgot them, so I kept them near the door. I felt more responsible because the habit was practical rather than expensive.", task:"准备 1 分钟，用 5 个笔记点连续说 90 秒；第二遍加入 conservation 或 consumption。"},
      ece:{zh:"可持续实践在幼教中不是让儿童背环保口号，而是通过可重复使用材料、照料植物、减少浪费等日常活动培养尊重自然的习惯。", en:"Sustainable practice in early childhood is embedded in everyday routines, such as reusing materials, caring for plants and reducing waste.", terms:[["sustainable practice","可持续实践","在日常决策中减少浪费并尊重自然"],["natural materials","自然材料","树叶、石头、木块等可探索材料"],["kaitiakitanga","守护与照料的责任","新西兰语境中与守护土地、环境相关的理念"]], scenario:"Children collect leaves for a collage. 练习：I observed… / This supported respect for… / Next time, I would…"}
    },
    {
      key:"day6", label:"Day 6 · 2026.08.22", date:"2026-08-22", theme:"Work & Employment｜工作、技能与自动化", previous:"Day 5 环境词汇、条件句与 T/F/NG 判断", eceTitle:"Partnerships with Families｜与家庭建立伙伴关系",
      focus:[["employment","n. /ɪmˈplɔɪmənt/","就业；雇用","employment opportunities / full-time employment","Employment opportunities are limited in some regions.","Training can improve employment prospects for people changing careers.","employ 是动词；employment 通常不可数。","______ can create employment opportunities."],["automation","n. /ˌɔːtəˈmeɪʃn/","自动化","workplace automation / automate tasks","Automation can complete repetitive tasks quickly.","Workplace automation may change the skills that employees need.","常写 automation rather than automatic technology。","Automation may affect ______ by ______."],["productivity","n. /ˌprɒdʌkˈtɪvəti/","生产率；工作效率","increase productivity / worker productivity","Good planning can increase productivity.","Flexible schedules may improve productivity for some employees.","productive 为形容词。","______ can improve productivity because ______."],["qualification","n. /ˌkwɒlɪfɪˈkeɪʃn/","资格；学历","professional qualification / relevant qualifications","Applicants need relevant qualifications.","In a changing labour market, workers may need to update their qualifications.","复习 Day 1：qualification 是资格/学历，不等于 degree。","My qualifications include ______."],["workload","n. /ˈwɜːkləʊd/","工作量","heavy workload / manage workload","A heavy workload can cause stress.","Employers should help staff manage workload during busy periods.","通常不可数。","A heavy workload may lead to ______."]],
      quick:[["employee","n. /ɪmˈplɔɪiː/","雇员","skilled employee"],["employer","n. /ɪmˈplɔɪə(r)/","雇主","responsible employer"],["salary","n. /ˈsæləri/","工资","competitive salary"],["vacancy","n. /ˈveɪkənsi/","职位空缺","job vacancy"],["recruit","v. /rɪˈkruːt/","招聘","recruit staff"],["training","n. /ˈtreɪnɪŋ/","培训","job training"],["promotion","n. /prəˈməʊʃn/","晋升","career promotion"],["flexible","adj. /ˈfleksəbl/","灵活的","flexible working"],["remote","adj. /rɪˈməʊt/","远程的","remote work"],["labour","n. /ˈleɪbə(r)/","劳动力","labour market"],["career","n. /kəˈrɪə(r)/","职业生涯","career path"],["specialise","v. /ˈspeʃəlaɪz/","专攻","specialise in"],["repetitive","adj. /rɪˈpetətɪv/","重复的","repetitive task"],["adapt","v. /əˈdæpt/","适应","adapt to change"],["efficient","adj. /ɪˈfɪʃnt/","高效的","efficient system"]],
      grammar:{title:"名词从句与报告观点",goal:"用 It is widely believed that…、Many people argue that… 和 whether 表达工作类抽象观点。",rows:[["It is widely believed that + 句子","中立引入普遍观点","It is widely believed that automation will change employment."],["Many people argue that + 句子","引入可讨论观点","Many people argue that remote work improves work-life balance."],["whether + 句子","表示是否，常用于问题/讨论","It is unclear whether technology will replace all routine jobs."],["The fact that + 句子","把事实名词化","The fact that workers need retraining is widely recognised."]],error:"❌ Many people argue automation is useful.（口语可用，但写作建议加 that）\n✅ Many people argue that automation is useful.",exercise:"1. 人们相信培训能改善就业。\n2. 是否远程办公提高效率尚不明确。\n3. 工人需要适应变化这一事实很重要。",answer:"1. It is widely believed that training can improve employment.\n2. It is unclear whether remote work improves productivity.\n3. The fact that workers need to adapt to change is important."},
      listening:{title:"Section 3｜大学职业研究小组讨论",scenario:"两名学生与导师讨论研究任务。Part 3 常考观点对应、选择与修改意见。",questions:["1. The students will compare two age ______.","2. They will use government labour ______.","3. The tutor says their first survey question is too ______.","4. The final presentation should include one case ______."],text:"Tutor: Your project on automation and work is promising. Which groups will you compare? Student: We plan to compare two age groups: recent graduates and workers over fifty. Tutor: Good. Where will you find background data? Student: We will use government labour statistics. Tutor: Your first survey question is too general. Ask about a specific task instead. Student: We will also include one case study of a company that retrained staff.",answer:"groups；statistics；general；study。",substitution:"background data = statistics；too broad = too general；retrained staff = gave workers new training。",task:"边听边标出是谁提出的信息；再口头说明研究会比较什么、使用什么数据、怎样改进问卷。"},
      reading:{title:"True / False / Not Given｜远程工作的影响",type:"题目中的 all、only、always 等绝对词要格外警惕；不要用常识补充原文。",passage:["Remote work has expanded in many industries, although it is not possible for every occupation. For some employees, working from home saves commuting time and allows a more flexible schedule. Nevertheless, the benefits are not shared equally. People who live in crowded homes may find it difficult to create a quiet workspace, while new employees can miss informal learning from colleagues. Several companies have therefore adopted hybrid arrangements, in which staff divide their time between home and a shared workplace. Researchers are still examining the long-term effect of these arrangements on productivity and wellbeing."],questions:["1. Remote work is possible in every type of job.","2. Working from home can save some employees travel time.","3. New employees may have fewer informal learning opportunities at home.","4. All companies have replaced offices with home working.","5. The text gives a final conclusion about the long-term effect on productivity."],answer:"1 False：not possible for every occupation。2 True：saves commuting time。3 True：can miss informal learning。4 False：several companies adopted hybrid arrangements。5 Not Given：researchers are still examining。"},
      writing:{title:"Academic Task 1｜流程图：在线职位申请",prompt:"下图说明求职者在线申请职位的流程。概括主要阶段并比较或说明关键步骤。",table:[["步骤","内容"],["1","在公司网站创建账号并上传简历"],["2","系统筛选基本资格并发送确认邮件"],["3","合格申请者完成在线测试"],["4","招聘人员审核结果并安排面试"],["5","公司向成功申请者发出录用通知"]],plan:"Introduction：说明图表展示在线申请流程。Overview：流程共五步，从创建账号到录用通知；筛选和测试发生在面试之前。主体：按顺序写，使用 first, once, after that, finally。",band:"Once the applicant has uploaded a CV, the system checks whether the basic qualifications are met. Applicants who pass this stage are invited to complete an online assessment before their results are reviewed by recruitment staff.",task:"写 5 句步骤描述，至少使用 once、after that、before 和 finally 各一次。"},
      speaking:{title:"Part 3｜未来的工作与技能",questions:["Which skills will be important in future jobs?", "Should companies train employees or should workers pay for their own training?", "Do you think automation will create more jobs than it removes?"],structure:"观点 → 原因 → 例子/限制。Part 3 可用 In my view, One reason is that…, However, this depends on…。",sample:"In my view, adaptability and communication will remain important because technology changes tasks more quickly than before. For example, even when routine work is automated, employees still need to explain problems and cooperate with clients. However, technical training is also necessary.",task:"回答第 2 题 45 秒；必须出现 one reason、for example 和 however。"},
      ece:{zh:"在 NZTC 课堂中，partnerships with families 强调教师把家庭视为儿童学习的重要知识来源。交流要尊重、具体，并避免只在出现问题时联系家长。",en:"Partnerships with families recognise that families know their children well. Teachers communicate respectfully, share specific observations and invite family perspectives.",terms:[["family voice","家庭声音/观点","邀请家庭分享儿童兴趣、语言和习惯"],["reciprocal communication","双向沟通","教师与家庭互相交流，而非单向通知"],["strength-based approach","优势导向方式","先看儿童及家庭已有的能力和资源"]],scenario:"A parent says their child has recently become interested in cooking. 练习：Thank you for sharing… / I have noticed… / We could…"}
    },
    {
      key:"day7", label:"Day 7 · 2026.08.23", date:"2026-08-23", theme:"Housing & Urban Life｜住房、城市生活与社区", previous:"Day 6 工作词汇、名词从句与工作场景判断题", eceTitle:"Learning Environments｜学习环境与材料布置",
      focus:[["affordable","adj. /əˈfɔːdəbl/","负担得起的","affordable housing / affordable price","The rent is not affordable for many students.","Cities need more affordable housing near public transport.","affordable to + 人；affordable housing 固定搭配。","______ should be affordable to ______."],["accommodation","n. /əˌkɒməˈdeɪʃn/","住宿；住处","student accommodation / temporary accommodation","Students often look for accommodation near campus.","A shortage of rental accommodation can force workers to live far from the city centre.","英式英语中常不可数。","There is a shortage of ______ accommodation."],["residential","adj. /ˌrezɪˈdenʃl/","住宅区的；居住的","residential area / residential building","This is a quiet residential area.","New residential developments should include parks and local services.","residence 是住所；residential 是形容词。","A residential area should provide ______."],["density","n. /ˈdensəti/","密度","population density / high-density housing","Population density is high in the city centre.","High-density housing can be practical if public spaces are well designed.","high-density 是常见连字符搭配。","High population density may result in ______."],["infrastructure","n. /ˈɪnfrəstrʌktʃə(r)/","基础设施","urban infrastructure / public infrastructure","Reliable infrastructure supports daily life.","Housing growth must be matched by investment in transport infrastructure.","复习 Day 3：通常不可数。","The government should invest in ______ infrastructure."]],
      quick:[["rent","n./v. /rent/","租金；租用","pay rent"],["tenant","n. /ˈtenənt/","租户","protect tenants"],["landlord","n. /ˈlændlɔːd/","房东","private landlord"],["property","n. /ˈprɒpəti/","房产；财产","property prices"],["neighbourhood","n. /ˈneɪbəhʊd/","社区；街区","safe neighbourhood"],["facility","n. /fəˈsɪləti/","设施","public facilities"],["commute","n./v. /kəˈmjuːt/","通勤","long commute"],["suburb","n. /ˈsʌbɜːb/","郊区","outer suburb"],["crowded","adj. /ˈkraʊdɪd/","拥挤的","crowded area"],["maintain","v. /meɪnˈteɪn/","维护；维持","maintain buildings"],["develop","v. /dɪˈveləp/","开发；发展","develop housing"],["local","adj. /ˈləʊkl/","当地的","local services"],["public","adj. /ˈpʌblɪk/","公共的","public space"],["convenient","adj. /kənˈviːniənt/","方便的","convenient location"],["shortage","n. /ˈʃɔːtɪdʒ/","短缺","housing shortage"]],
      grammar:{title:"关系从句：定义人与地点",goal:"使用 who、which、that、where 让 Task 2 与口语的句子更精确。",rows:[["people who + 动词","修饰人","Tenants who live far from work may face long commutes."],["things which/that + 动词","修饰物","Housing that is close to transport is often more expensive."],["place where + 句子","修饰地点","A neighbourhood where children can play safely is attractive to families."],["名词, which + 动词","补充说明整件事","The city expanded rapidly, which increased pressure on services."]],error:"❌ The area where has many parks is popular. ✅ The area which has many parks is popular.\n❌ A place which people live is… ✅ A place where people live is…",exercise:"1. 政府应帮助租金高的租户。（who）\n2. 公共交通便利的住房很受欢迎。（that）\n3. 我想住在有图书馆的社区。（where）",answer:"1. Governments should help tenants who face high rents.\n2. Housing that has convenient public transport is popular.\n3. I would like to live in a neighbourhood where there is a library."},
      listening:{title:"Section 2｜新社区导览与地图定位",scenario:"单人说明通常按路线介绍地点。先在地图上找入口、方向词和已有地标。",questions:["1. The community centre is next to the ______.","2. The library is opposite the ______.","3. The children's play area is behind the ______.","4. The guided walk begins at the main ______."],text:"Guide: Welcome to Riverside Community. The community centre is beside the health clinic, near the southern entrance. Across from the centre, you can see the public library. Behind the library is a children's play area. Our guided walk begins at the main gate at ten o'clock, so please meet there five minutes earlier.",answer:"health clinic；community centre；library；gate。",substitution:"beside = next to；across from = opposite；begins = starts。",task:"在纸上画四个方框完成简图；再用 next to、opposite、behind 介绍路线。"},
      reading:{title:"Summary Completion｜住房与通勤",type:"答案通常集中在原文的一部分；先读 summary 判断词性，再回原文找同义句，严格遵守词数限制。",passage:["Rising housing costs have changed commuting patterns in many large cities. Some employees choose to live in outer suburbs because rents are lower there, but this can mean spending more time travelling to work. Long commutes may reduce the time available for family life, exercise and rest. City planners are therefore considering mixed-use neighbourhoods, where homes, shops and workplaces are located closer together. Supporters argue that these areas can reduce car dependence and make local services easier to reach. Critics point out, however, that new developments must be planned carefully so that they do not simply increase population density without improving transport and public facilities."],questions:["Complete the summary. People may move to outer suburbs because ______ are lower. However, long ______ can reduce time for rest. Mixed-use areas aim to reduce dependence on ______ and improve access to local ______."],answer:"rents；commutes；cars；services。定位：lower rents → rents are lower；spending more time travelling → long commutes；car dependence → dependence on cars；local services → services。"},
      writing:{title:"Academic Task 2｜同意或不同意",prompt:"Some people think governments should spend more money on building new homes, while others believe that improving existing housing is more important. To what extent do you agree or disagree?",plan:"立场：两者都重要，但在住房短缺地区新建住房应优先，同时必须维护既有住房。主体 1：新建解决供应不足、靠近设施的规划。主体 2：维护影响安全、能源效率、租户生活质量。",band:"Although renovating older buildings can improve safety and reduce energy use, it cannot by itself address a severe shortage of homes. I therefore believe that construction should be prioritised where demand clearly exceeds supply.",task:"写 introduction 2 句 + 一个主体段 5 句。必须明确你的程度立场，不要只列出两边。"},
      speaking:{title:"Part 1｜Home and Neighbourhood",questions:["Do you live in a house or an apartment?", "What do you like about your neighbourhood?", "Would you like to move to a different place in the future?"],structure:"给出具体细节：位置、设施、噪音、通勤或邻里关系。",sample:"I live in an apartment in a fairly convenient neighbourhood. What I like most is that there is a supermarket and a bus stop within walking distance, so I do not need to drive for everyday errands.",task:"回答三题中的两题，每题 30 秒；第二次加入 residential、convenient 或 affordable。"},
      ece:{zh:"学习环境不仅是教室装饰。教师通过可选择的材料、清晰的区域和可达的资源，邀请儿童自主探索并与他人合作。",en:"A learning environment is more than decoration. It offers accessible materials, clear areas and choices that invite children to explore independently and with others.",terms:[["learning environment","学习环境","空间、材料、关系与日常安排共同构成"],["open-ended materials","开放性材料","没有唯一玩法，如积木、布料、自然物"],["accessibility","可达性","儿童能安全、独立地拿取和使用资源"]],scenario:"A child cannot reach the art materials. 练习：I noticed… / To make the area more accessible, I would…"}
    },
    {
      key:"day8", label:"Day 8 · 2026.08.24", date:"2026-08-24", theme:"Science & Research｜科学、研究与创新", previous:"Day 7 住房词汇、关系从句与总结填空", eceTitle:"Observation & Documentation｜观察与学习记录",
      focus:[["hypothesis","n. /haɪˈpɒθəsɪs/","假设","test a hypothesis / research hypothesis","The researchers tested their hypothesis.","A useful hypothesis gives a study a clear question to investigate.","复数 hypotheses。","The hypothesis is that ______."],["variable","n. /ˈveəriəbl/","变量","control a variable / key variable","Age was an important variable in the study.","Researchers need to control variables when comparing two groups.","variable 也可作形容词“可变的”。","One important variable is ______."],["data","n. /ˈdeɪtə/","数据","collect data / analyse data","The team collected data from 200 participants.","Reliable data allows researchers to identify patterns rather than rely on opinions.","写作中可配合 plural verb：data show；现代英语也常 data shows。","The data show that ______."],["innovation","n. /ˌɪnəˈveɪʃn/","创新","technological innovation / encourage innovation","Innovation can improve medical treatment.","Public funding may encourage innovation in clean energy research.","innovate 是动词。","Innovation in ______ can lead to ______."],["ethical","adj. /ˈeθɪkl/","伦理的；道德的","ethical issue / ethical research","Researchers must consider ethical issues.","Ethical research protects participants' privacy and informed consent.","ethics 是名词。","It is ethical to ______ when ______."]],
      quick:[["experiment","n./v. /ɪkˈsperɪmənt/","实验","conduct an experiment"],["researcher","n. /rɪˈsɜːtʃə(r)/","研究者","medical researcher"],["participant","n. /pɑːˈtɪsɪpənt/","参与者","study participant"],["sample","n. /ˈsɑːmpl/","样本","large sample"],["result","n. /rɪˈzʌlt/","结果","research result"],["analyse","v. /ˈænəlaɪz/","分析","analyse data"],["method","n. /ˈmeθəd/","方法","research method"],["evidence","n. /ˈevɪdəns/","证据","scientific evidence"],["discover","v. /dɪˈskʌvə(r)/","发现","discover a link"],["laboratory","n. /ləˈbɒrətri/","实验室","research laboratory"],["measure","v. /ˈmeʒə(r)/","测量","measure change"],["reliable","adj. /rɪˈlaɪəbl/","可靠的","reliable result"],["accurate","adj. /ˈækjərət/","准确的","accurate measurement"],["theory","n. /ˈθɪəri/","理论","scientific theory"],["funding","n. /ˈfʌndɪŋ/","资金","research funding"]],
      grammar:{title:"被动语态：描述研究与流程",goal:"在 Task 1 流程图和学术描述中，使用被动语态突出过程，而不是操作者。",rows:[["be + 过去分词","一般被动","Data are collected from participants."],["is/are then + 过去分词","步骤顺序","The samples are then analysed in a laboratory."],["was/were + 过去分词","过去研究","The experiment was conducted over six weeks."],["by + 执行者","需要时才说明执行者","The results were checked by two researchers."]],error:"❌ The data collected by researchers. ✅ The data were collected by researchers.\n❌ Participants are asked to complete a survey and analyse. ✅ Participants are asked to complete a survey, and the data are analysed.",exercise:"1. 研究者收集数据。（用被动）\n2. 然后对结果进行比较。\n3. 实验在实验室中进行。",answer:"1. Data are collected by researchers.\n2. The results are then compared.\n3. The experiment is conducted in a laboratory."},
      listening:{title:"Section 4｜海洋研究流程图",scenario:"流程图题先看箭头和空格前后词性。注意录音会用不同动词描述同一步骤。",questions:["1. Water samples are taken from different ______.","2. The samples are kept at a low ______.","3. Scientists measure the level of ______ in the water.","4. The results are compared with earlier ______."],text:"Lecturer: To study changes in coastal water, researchers first take samples from different depths. The containers are kept at a low temperature during transport. In the laboratory, scientists measure the level of oxygen in each sample. Finally, the results are compared with records from previous years to identify long-term changes.",answer:"depths；temperature；oxygen；records。",substitution:"taken = collected；kept at a low temperature = cooled；earlier records = records from previous years。",task:"画出四步箭头图；跟读时重点练被动：are taken, are kept, are compared。"},
      reading:{title:"Matching Headings｜科学传播",type:"Heading 要抓段落核心，不要被某个例子带走。先为每段写 3–5 个中文关键词再选。",passage:["A  Scientific findings can be difficult for the public to understand because research papers often use specialised language. A clear explanation must simplify ideas without changing the evidence.","B  Visual material such as diagrams, short videos and data graphics can help audiences notice patterns. However, visuals need accurate labels, otherwise they may create a misleading impression.","C  Some scientists now work directly with local communities. Residents may help collect observations, for example by recording bird sightings or air quality readings.","D  Fast online communication allows research news to spread quickly. The disadvantage is that unverified claims can also reach large audiences before they are corrected."],questions:["i Involving non-specialists in gathering information", "ii The risk of speed without checking", "iii Making difficult ideas understandable", "iv Why visual material can be misleading", "v Replacing researchers with computers"],answer:"A–iii；B–iv；C–i；D–ii；v 不使用。每段关键词：A specialised language/clear explanation；B visuals/accurate labels；C communities/collect observations；D fast online/unverified claims。"},
      writing:{title:"Academic Task 1｜柱状图：科研经费来源",prompt:"下表显示 2010 和 2020 年某国三类科研经费占比。概括主要特征并比较。",table:[["来源","2010","2020"],["政府","50%","42%"],["企业","30%","40%"],["大学","20%","18%"]],plan:"Overview：政府仍为最大来源但下降；企业上升并接近政府；大学略降。Body：比较政府/企业的反向趋势，再写大学。",band:"Government funding remained the largest source in both years, although its share fell by eight percentage points. In contrast, the proportion provided by businesses rose from 30% to 40%.",task:"写 introduction、overview 和两句精确数字比较。使用 remained、although、in contrast。"},
      speaking:{title:"Part 2｜一次有用的科学学习经历",questions:["Describe a science lesson or experiment that you found useful.","You should say when you had it, what you learned, what you did, and explain why it was useful."],structure:"按时间顺序讲：背景 → 活动 → 发现 → 为什么有用。加入一个具体细节避免空泛。",sample:"I once attended a short lesson about water quality. We tested samples with simple strips and compared the colours. It was useful because I had previously thought that clear water was always clean. The activity showed me that scientific evidence can challenge everyday assumptions.",task:"写 6 个关键词，准备 1 分钟后说 90 秒；第二遍加入 hypothesis 或 evidence。"},
      ece:{zh:"观察记录的重点是描述可见、可听到的行为，而不是马上给儿童贴标签。之后再思考学习可能是什么，以及教师的下一步支持。",en:"Observation documentation begins with what can be seen and heard. Teachers then interpret possible learning and plan a responsive next step.",terms:[["objective observation","客观观察","先记录行为，不先写‘他很懒/她不专心’"],["learning story","学习故事","以叙事方式记录儿童的兴趣、能力和学习过程"],["next step","下一步支持","基于观察而设计的后续邀请或资源"]],scenario:"A child repeats a ramp experiment after the first car stops too early. 练习：I observed… / This may show… / Next time, I would…"}
    },
    {
      key:"day9", label:"Day 9 · 2026.08.25", date:"2026-08-25", theme:"Culture & Tourism｜文化、旅游与遗产保护", previous:"Day 8 科研词汇、被动语态与 Matching Headings", eceTitle:"Bicultural Practice｜双文化实践与归属感",
      focus:[["heritage","n. /ˈherɪtɪdʒ/","遗产；传统","cultural heritage / protect heritage","The town is proud of its cultural heritage.","Tourism revenue can help protect heritage sites when it is managed responsibly.","heritage 可指有形建筑或无形传统。","______ is an important part of cultural heritage."],["preservation","n. /ˌprezəˈveɪʃn/","保存；保护","historic preservation / preservation of","The preservation of old buildings can be expensive.","The preservation of local traditions requires support from younger generations.","preserve 为动词。","The preservation of ______ depends on ______."],["authentic","adj. /ɔːˈθentɪk/","真实的；原汁原味的","authentic experience / authentic culture","Visitors want an authentic experience.","Local guides can offer a more authentic understanding of a region than generic advertisements.","注意不是 authority。","An authentic experience should include ______."],["revenue","n. /ˈrevənjuː/","收入；财政收入","tourism revenue / generate revenue","Tourism generates revenue for local businesses.","Tourism revenue should partly fund the maintenance of public heritage sites.","正式语境常不可数。","Tourism can generate revenue for ______."],["overcrowding","n. /ˌəʊvəˈkraʊdɪŋ/","过度拥挤","tourist overcrowding / prevent overcrowding","Overcrowding can damage popular sites.","Visitor limits may be necessary to prevent overcrowding at fragile locations.","crowded 是形容词；overcrowding 是问题名词。","Overcrowding may cause ______."]],
      quick:[["tourist","n. /ˈtʊərɪst/","游客","international tourist"],["destination","n. /ˌdestɪˈneɪʃn/","目的地","popular destination"],["attraction","n. /əˈtrækʃn/","景点；吸引力","tourist attraction"],["visitor","n. /ˈvɪzɪtə(r)/","访客","visitor number"],["local","adj. /ˈləʊkl/","当地的","local culture"],["tradition","n. /trəˈdɪʃn/","传统","local tradition"],["museum","n. /mjuːˈziːəm/","博物馆","national museum"],["guide","n./v. /ɡaɪd/","导游；引导","tour guide"],["crowd","n./v. /kraʊd/","人群；拥挤","large crowd"],["respect","n./v. /rɪˈspekt/","尊重","show respect for"],["maintain","v. /meɪnˈteɪn/","维护","maintain a site"],["economic","adj. /ˌiːkəˈnɒmɪk/","经济的","economic benefit"],["seasonal","adj. /ˈsiːzənl/","季节性的","seasonal employment"],["promote","v. /prəˈməʊt/","促进；推广","promote tourism"],["resident","n. /ˈrezɪdənt/","居民","local resident"]],
      grammar:{title:"非限定性补充信息与举例",goal:"用 which、such as、including 和 for example 为口语与写作补充具体信息。",rows:[["名词, which + 动词","补充前面整件事","Tourism creates jobs, which can benefit local residents."],["such as + 名词","列举例子","Sites such as museums and temples need careful maintenance."],["including + 名词/动名词","包含其中项目","Visitors can learn through activities including guided walks."],["for example","完整句举例","For example, visitor limits can protect fragile areas."]],error:"❌ Such as museums are popular. ✅ Museums, such as the national museum, are popular.\n❌ Tourism brings benefits, for example jobs. ✅ Tourism brings benefits, such as jobs.",exercise:"1. 旅游创造收入，这可支持遗产保护。（which）\n2. 博物馆和历史建筑需要维护。（such as）\n3. 给出一个游客限制的例子。（for example）",answer:"1. Tourism creates revenue, which can support heritage preservation.\n2. Sites such as museums and historic buildings need maintenance.\n3. For example, visitor limits can reduce overcrowding."},
      listening:{title:"Section 1｜博物馆参观预订",scenario:"预约类对话关注日期、人数、时间和附加服务。注意数字可能被更正。",questions:["1. The group will visit on ______ 14th.","2. There will be ______ students in the group.","3. The guided tour starts at ______ a.m.","4. Lunch will be eaten in the ______ garden."],text:"Visitor: We would like to book a school visit for Friday the fourteenth. At first I thought there would be thirty students, but two are absent, so the final number is twenty-eight. The guided tour begins at ten thirty in the morning. After the exhibition, the group may eat lunch in the sculpture garden if the weather is fine.",answer:"Friday；28；10.30；sculpture。",substitution:"book = reserve；final number = actual number；begins = starts；if weather is fine = if it does not rain。",task:"圈出先出现后被更正的数字；听读两遍后写一段 3 句预约确认信息。"},
      reading:{title:"Multiple Choice｜旅游的影响",type:"选择题通常按原文顺序出现。先找题干关键词，再比较每个选项是否准确概括，不要只选出现原词的选项。",passage:["Tourism can provide employment and income, particularly in places with few other industries. It can also encourage investment in transport, museums and public spaces. Yet rapid growth can put pressure on housing and local services, especially when short-term accommodation becomes more profitable than long-term rentals. Some destinations have introduced visitor limits during peak seasons. These policies are not intended to stop tourism completely; instead, they aim to spread visits across different times and locations. Researchers suggest that local residents should be included in planning, since they experience both the economic benefits and the daily effects of visitor numbers."],questions:["1. What is the writer's main point about visitor limits?\nA They should end tourism.  B They can manage when and where people visit.  C They are only useful for museums.  D They reduce all housing costs.","2. Why should residents be involved in planning?\nA They know only about transport.  B They pay for all attractions.  C They experience both benefits and pressures.  D They prefer peak-season travel."],answer:"1 B：spread visits across different times and locations。2 C：experience both economic benefits and daily effects。排除：A 与 not intended to stop tourism 相反；D 文中未说；B 过度缩小范围。"},
      writing:{title:"Academic Task 2｜双问题：旅游与当地居民",prompt:"International tourism has increased in many countries. What benefits does this bring to local people? What problems can it cause for local communities?",plan:"先分别回答两个问题。主体 1：就业、收入、基础设施投入。主体 2：过度拥挤、住房压力、文化商品化风险。结论：可持续旅游与居民参与规划。",band:"One clear benefit is that tourism creates employment not only in hotels and transport but also in small local businesses. Nevertheless, if visitor numbers grow without planning, residents may face overcrowded services and rising rental costs.",task:"写两个 topic sentence 和每段各两个支持句；检查是否两个问题都直接回答。"},
      speaking:{title:"Part 3｜旅游、文化与保护",questions:["Why do people like visiting historical places?", "Can tourism damage local culture?", "Who should pay to protect heritage sites?"],structure:"回答抽象问题时可用“主要原因 + 例子 + 条件/限制”。",sample:"People often visit historical places because they want a direct connection with the past. For example, seeing an old building can make history feel more concrete than reading about it. However, tourism needs to be managed so that local residents do not lose access to their own public spaces.",task:"回答第 2 题 45 秒；使用 heritage、overcrowding 和 however 各一次。"},
      ece:{zh:"双文化实践不是在活动中偶尔加入几个词，而是尊重 Aotearoa New Zealand 的 Te Tiriti 关系、儿童家庭的语言与文化，并让这些内容自然进入日常环境和交流。",en:"Bicultural practice involves respecting Te Tiriti relationships, children's languages and cultures, and making these visible in everyday environments and communication.",terms:[["bicultural practice","双文化实践","在新西兰幼教中尊重 Māori 与 Pākehā 的伙伴关系"],["mana","尊严、权威与精神力量","支持儿童的自信、归属和被尊重感"],["whānau","家庭/扩展家庭","比狭义 family 更强调关系网络"]],scenario:"A whānau shares a greeting used at home. 练习：Thank you for sharing… / We would like to include… / This can strengthen…"}
    }
  ];

  const day3ReviewData = {focus:[["advantage","","优点；优势","major advantage","","","","One advantage of ______ is that ______."],["drawback","","缺点；不利因素","potential drawback","","","","A drawback of ______ is ______."],["contribute","","促成；贡献","contribute to","","","","______ can contribute to ______."],["effective","","有效的","effective method","","","","______ is an effective way to ______."],["concern","","担忧；使担心","raise concerns","","","","One concern is that ______."]],quick:[["device","","设备","digital device"],["digital","","数字化的","digital technology"],["screen","","屏幕","screen time"],["resource","","资源","learning resources"],["flexible","","灵活的","flexible schedule"],["convenient","","方便的","convenient access"],["distract","","使分心","distract students from"],["interaction","","互动","social interaction"],["privacy","","隐私","protect privacy"],["reliable","","可靠的","reliable information"],["replace","","取代","replace traditional methods"],["balance","","平衡","strike a balance"],["traditional","","传统的","traditional classroom"],["independent","","独立的","independent learning"],["engagement","","参与度","student engagement"]],grammar:{goal:"复习 although、despite、however 与 whereas 的让步和对比表达。"},listening:{substitution:"took part = participated；valued = considered important；remain focused = avoid distraction；improve engagement = encourage active participation。"},reading:{title:"True / False / Not Given｜教育科技判断题"},writing:{title:"Task 2 教育科技利弊题"},eceTitle:"Intentional use of digital technology｜数字技术的有意识使用"};
  function wordCards(words) {
    return words.map(([word, pron, chinese, collocations, base, topic, tip, prompt]) => `<article class='word-card'><h3>${word}</h3><p>${pron} · ${chinese}</p><p><strong>搭配：</strong>${collocations}</p><p><strong>基础例句：</strong>${base}</p><p><strong>主题例句：</strong>${topic}</p><p><strong>提示：</strong>${tip}</p><p><strong>My Sentence：</strong>${prompt}</p></article>`).join("");
  }
  function quickTable(words) {
    return words.map(([word,pos,cn,col]) => `<tr><td>${word}</td><td>${pos}</td><td>${cn}</td><td>${col}</td></tr>`).join("");
  }
  function reviewHtml(day, prev) {
    const previous = days4to9.find(d => d.key === prev) || (prev === "day3" ? day3ReviewData : null);
    const focus = previous ? previous.focus : [];
    const quick = previous ? previous.quick : [];
    return `<h3>${day.previous}｜完整复习</h3><div class='review-modules'>
      <article class='review-module-card'><h4>1. 五个重点词｜回忆 + 搭配 + 造句</h4><table><thead><tr><th>单词</th><th>中文</th><th>关键搭配</th><th>口头提示</th></tr></thead><tbody>${focus.map(x=>`<tr><td>${x[0]}</td><td>${x[2]}</td><td>${x[3]}</td><td>${x[7]}</td></tr>`).join("")}</tbody></table><div class='answer'><strong>任务：</strong>遮住中文与搭配，先说词性、含义和一个搭配；再任选 3 词造句。不要只读答案。</div></article>
      <article class='review-module-card'><h4>2. Quick Words｜15 词分类回忆</h4><table><thead><tr><th>单词</th><th>中文</th><th>搭配</th></tr></thead><tbody>${quick.map(x=>`<tr><td>${x[0]}</td><td>${x[2]}</td><td>${x[3]}</td></tr>`).join("")}</tbody></table><div class='answer'><strong>自测：</strong>从上表任选 5 词，先说中文，再说搭配，最后造句。第二遍只看中文回忆英文。</div></article>
      <article class='review-module-card'><h4>3. Grammar｜规则与改写</h4><p><strong>昨日目标：</strong>${previous ? previous.grammar.goal : "复习前一日语法"}</p><p><strong>口头改写：</strong>从昨日的三个练习中任选两题，不看答案完成；再检查句子是否有完整谓语、正确连接词和正确词性。</p><div class='answer'><strong>复盘原则：</strong>先确认结构，再替换词汇。若错误，写出正确句并朗读两遍。</div></article>
      <article class='review-module-card'><h4>4. 听力与阅读｜定位技能回忆</h4><p><strong>昨日听力同义：</strong>${previous ? previous.listening.substitution : "复习关键词"}</p><p><strong>昨日阅读类型：</strong>${previous ? previous.reading.title : "阅读定位"}</p><div class='answer'><strong>任务：</strong>不看文本，说出昨日听力答案的两项定位依据；阅读题先圈题干关键词，再回原文找同义句。</div></article>
      <article class='review-module-card'><h4>5. 写作、口语与 NZTC｜主动输出</h4><p><strong>写作：</strong>${previous ? previous.writing.title : "复述写作结构"}；用一句 overview 或 topic sentence 复述昨日观点。</p><p><strong>口语：</strong>用“直接回答 → 原因 → 具体例子”重答昨日一个问题。</p><p><strong>NZTC：</strong>${previous ? previous.eceTitle : "观察与反思"}；用 I observed… / This supported… / Next time, I would… 完成微型反思。</p></article></div>`;
  }
  function englishHtml(d) {
    const g = d.grammar;
    return `<div class='details-list'>
      <details open><summary>1. 重点词汇卡｜Academic Vocabulary</summary><p>先读搭配与例句，再写自己的句子。今天的 IELTS 主题是“${d.theme.split("｜")[0]}”，不需要与 NZTC 内容强行绑定。</p><div class='word-grid'>${wordCards(d.focus)}</div></details>
      <details class='quick-words-card'><summary>2. Quick Words｜快速积累 15 词</summary><p>每个词先掌握词义与搭配；当天至少选 5 个词造句，并在晚上只看中文回忆英文。</p><table><thead><tr><th>单词</th><th>词性与发音</th><th>中文</th><th>常用搭配</th></tr></thead><tbody>${quickTable(d.quick)}</tbody></table><div class='answer'><strong>自测步骤：</strong><br>1. 从表中选 5 词，说出中文。<br>2. 说出一个搭配。<br>3. 用其中 3 词说出完整句。<br><br><strong>提醒：</strong>搭配比孤立中文更适合雅思写作与口语输出。</div></details>
      <details class='grammar-card'><summary>3. Grammar｜${g.title}</summary><p><strong>目标：</strong>${g.goal}</p><table><thead><tr><th>结构</th><th>使用规则</th><th>例句</th></tr></thead><tbody>${g.rows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join("")}</tbody></table><div class='answer'><strong>常见错误：</strong><br>${g.error.replace(/\n/g,"<br>")}<br><br><strong>改写练习：</strong><br>${g.exercise.replace(/\n/g,"<br>")}<br><br><strong>参考答案：</strong><br>${g.answer.replace(/\n/g,"<br>")}</div></details>
      <details><summary>4. 雅思听力｜${d.listening.title}</summary><p><strong>场景：</strong>${d.listening.scenario}</p><p><strong>听前预测：</strong>先看每个空格前后，判断需要数字、日期、名词或地点；注意题目规定的词数。</p><p><strong>题目：</strong><br>${d.listening.questions.join("<br>")}</p><p><strong>听读文本：</strong>${d.listening.text}</p><div class='answer'><strong>答案：</strong>${d.listening.answer}<br><strong>同义替换：</strong>${d.listening.substitution}<br><strong>任务：</strong>${d.listening.task}</div></details>
      <details><summary>5. 雅思阅读｜${d.reading.title}</summary><p><strong>做题策略：</strong>${d.reading.type}</p><p><strong>短文：</strong></p>${d.reading.passage.map(p=>`<p>${p}</p>`).join("")}<p><strong>题目：</strong></p><ol>${d.reading.questions.map(q=>`<li>${q.replace(/\n/g,"<br>")}</li>`).join("")}</ol><div class='answer'><strong>答案与定位：</strong>${d.reading.answer}</div></details>
      <details><summary>6. 雅思写作｜${d.writing.title}</summary><p><strong>题目：</strong>${d.writing.prompt}</p>${d.writing.table ? `<table><thead><tr>${d.writing.table[0].map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${d.writing.table.slice(1).map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join("")}</tr>`).join("")}</tbody></table>` : ""}<p><strong>审题与结构：</strong>${d.writing.plan}</p><div class='answer'><strong>7 分表达：</strong>${d.writing.band}<br><strong>今日任务：</strong>${d.writing.task}</div></details>
      <details><summary>7. 雅思口语｜${d.speaking.title}</summary><p><strong>真实题目：</strong></p><ol>${d.speaking.questions.map(q=>`<li>${q}</li>`).join("")}</ol><p><strong>扩展方法：</strong>${d.speaking.structure}</p><div class='answer'><strong>参考答案：</strong>${d.speaking.sample}<br><strong>开口任务：</strong>${d.speaking.task}</div></details></div>`;
  }
  function eceHtml(e) {
    return `<h3>${e.zh.split("。")[0]}｜双语课堂适应</h3><p><strong>中文：</strong>${e.zh}</p><p><strong>English：</strong>${e.en}</p><table><thead><tr><th>术语</th><th>中文</th><th>课堂理解</th></tr></thead><tbody>${e.terms.map(x=>`<tr><td>${x[0]}</td><td>${x[1]}</td><td>${x[2]}</td></tr>`).join("")}</tbody></table><div class='answer'><strong>情境练习：</strong>${e.scenario}<br><strong>目标：</strong>先用中文理解，再用 2–3 句简单英文表达观察、理解和下一步支持。</div>`;
  }
  const allExtraVocabulary = [];
  days4to9.forEach((d, index) => {
    const previous = index === 0 ? "day3" : days4to9[index - 1].key;
    days[d.key] = {label:d.label,date:d.date,title:`Day ${index + 4}｜Academic IELTS 7.0 + NZTC GD Readiness`,theme:d.theme,time:"标准版 90 分钟",tasks:[["复习",d.previous,"10 分钟"],["词汇 + 语法",`${d.theme.split("｜")[0]}学术词汇 + ${d.grammar.title}`,"15 分钟"],["雅思听力",d.listening.title,"15 分钟"],["雅思阅读",d.reading.title,"15 分钟"],["雅思写作",d.writing.title,"10 分钟"],["雅思口语",d.speaking.title,"5 分钟"],["NZTC GD 适应",d.eceTitle,"20 分钟"]],review:reviewHtml(d,previous),english:englishHtml(d),ece:eceHtml(d.ece)};
    d.focus.forEach(x => allExtraVocabulary.push([d.key,x[0],x[1],x[2],x[3]]));
    d.quick.forEach(x => allExtraVocabulary.push([d.key,x[0],x[1],x[2],x[3]]));
  });
  allExtraVocabulary.forEach(item => { if (!vocabulary.some(v => v[0] === item[0] && v[1] === item[1])) vocabulary.push(item); });
  // 新词根数据由 root-data.js 统一归档；若旧缓存尚未加载该辅助函数，使用同等的安全回退。
  if (typeof window.appendVocabularyRootFamilies !== "function") {
    window.appendVocabularyRootFamilies = function (entries) {
      window.vocabularyRootFamilies ||= [];
      entries.forEach(([, word, , meaning]) => {
        if (window.vocabularyRootFamilies.some(family => family.words.some(item => item.word === word))) return;
        window.vocabularyRootFamilies.push({root:word,source:"词形记忆单元",meaning:"以完整词义和搭配建立记忆",words:[{word,parts:`完整词形 ${word}（作为辅助记忆单元）`,meaning}]});
      });
    };
  }
  window.appendVocabularyRootFamilies(allExtraVocabulary);
  const filter = document.getElementById("vocabulary-day-filter");
  days4to9.forEach(d => { if (!filter.querySelector(`option[value='${d.key}']`)) filter.insertAdjacentHTML("beforeend", `<option value='${d.key}'>Day ${d.key.slice(3)}</option>`); });
  currentDay = state.currentDay && days[state.currentDay] ? state.currentDay : "day4";
  calendarDate = new Date(2026, 7, 20);
  renderDay();
  renderVocabulary();
  renderRootFamilyOptions();
})();
